// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	schema "github.com/archy-bold/mongo-go-helper/migration/schema"
	mock "github.com/stretchr/testify/mock"
)

// Migrator is an autogenerated mock type for the Migrator type
type Migrator struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, tasks
func (_m *Migrator) Run(ctx context.Context, tasks map[string]schema.TaskContract) error {
	ret := _m.Called(ctx, tasks)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]schema.TaskContract) error); ok {
		r0 = rf(ctx, tasks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
