// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	schema "github.com/archy-bold/mongo-go-helper/migration/schema"
	mock "github.com/stretchr/testify/mock"
)

// Seeder is an autogenerated mock type for the Seeder type
type Seeder struct {
	mock.Mock
}

// SeedData provides a mock function with given fields: ctx, task
func (_m *Seeder) SeedData(ctx context.Context, task *schema.SeedTableTask) error {
	ret := _m.Called(ctx, task)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *schema.SeedTableTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
